// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/reward_user_reward.proto

package earnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewardEarn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EarnId        string                 `protobuf:"bytes,1,opt,name=earn_id,json=earnId,proto3" json:"earn_id,omitempty"` // idempotency key
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`            // trip | order | campaign
	RefId         string                 `protobuf:"bytes,5,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"` // trip_id / order_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardEarn) Reset() {
	*x = RewardEarn{}
	mi := &file_proto_reward_user_reward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardEarn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardEarn) ProtoMessage() {}

func (x *RewardEarn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reward_user_reward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardEarn.ProtoReflect.Descriptor instead.
func (*RewardEarn) Descriptor() ([]byte, []int) {
	return file_proto_reward_user_reward_proto_rawDescGZIP(), []int{0}
}

func (x *RewardEarn) GetEarnId() string {
	if x != nil {
		return x.EarnId
	}
	return ""
}

func (x *RewardEarn) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RewardEarn) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *RewardEarn) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RewardEarn) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

var File_proto_reward_user_reward_proto protoreflect.FileDescriptor

const file_proto_reward_user_reward_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/reward_user_reward.proto\x12\vreward.earn\"\x83\x01\n" +
	"\n" +
	"RewardEarn\x12\x17\n" +
	"\aearn_id\x18\x01 \x01(\tR\x06earnId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x03R\x05point\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x15\n" +
	"\x06ref_id\x18\x05 \x01(\tR\x05refIdB(Z&reward-service/internal/pb/earn;earnpbb\x06proto3"

var (
	file_proto_reward_user_reward_proto_rawDescOnce sync.Once
	file_proto_reward_user_reward_proto_rawDescData []byte
)

func file_proto_reward_user_reward_proto_rawDescGZIP() []byte {
	file_proto_reward_user_reward_proto_rawDescOnce.Do(func() {
		file_proto_reward_user_reward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reward_user_reward_proto_rawDesc), len(file_proto_reward_user_reward_proto_rawDesc)))
	})
	return file_proto_reward_user_reward_proto_rawDescData
}

var file_proto_reward_user_reward_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_reward_user_reward_proto_goTypes = []any{
	(*RewardEarn)(nil), // 0: reward.earn.RewardEarn
}
var file_proto_reward_user_reward_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reward_user_reward_proto_init() }
func file_proto_reward_user_reward_proto_init() {
	if File_proto_reward_user_reward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reward_user_reward_proto_rawDesc), len(file_proto_reward_user_reward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reward_user_reward_proto_goTypes,
		DependencyIndexes: file_proto_reward_user_reward_proto_depIdxs,
		MessageInfos:      file_proto_reward_user_reward_proto_msgTypes,
	}.Build()
	File_proto_reward_user_reward_proto = out.File
	file_proto_reward_user_reward_proto_goTypes = nil
	file_proto_reward_user_reward_proto_depIdxs = nil
}
