// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/reward_redeem.proto

package redeempb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedeemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedeemId      string                 `protobuf:"bytes,1,opt,name=redeem_id,json=redeemId,proto3" json:"redeem_id,omitempty"` // idempotency key
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemRequest) Reset() {
	*x = RedeemRequest{}
	mi := &file_proto_reward_redeem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemRequest) ProtoMessage() {}

func (x *RedeemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reward_redeem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemRequest.ProtoReflect.Descriptor instead.
func (*RedeemRequest) Descriptor() ([]byte, []int) {
	return file_proto_reward_redeem_proto_rawDescGZIP(), []int{0}
}

func (x *RedeemRequest) GetRedeemId() string {
	if x != nil {
		return x.RedeemId
	}
	return ""
}

func (x *RedeemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RedeemRequest) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

type RedeemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedeemId      string                 `protobuf:"bytes,1,opt,name=redeem_id,json=redeemId,proto3" json:"redeem_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemResult) Reset() {
	*x = RedeemResult{}
	mi := &file_proto_reward_redeem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemResult) ProtoMessage() {}

func (x *RedeemResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reward_redeem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemResult.ProtoReflect.Descriptor instead.
func (*RedeemResult) Descriptor() ([]byte, []int) {
	return file_proto_reward_redeem_proto_rawDescGZIP(), []int{1}
}

func (x *RedeemResult) GetRedeemId() string {
	if x != nil {
		return x.RedeemId
	}
	return ""
}

func (x *RedeemResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RedeemResult) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *RedeemResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RedeemResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_reward_redeem_proto protoreflect.FileDescriptor

const file_proto_reward_redeem_proto_rawDesc = "" +
	"\n" +
	"\x19proto/reward_redeem.proto\x12\rreward.redeem\"[\n" +
	"\rRedeemRequest\x12\x1b\n" +
	"\tredeem_id\x18\x01 \x01(\tR\bredeemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x03R\x05point\"\x8c\x01\n" +
	"\fRedeemResult\x12\x1b\n" +
	"\tredeem_id\x18\x01 \x01(\tR\bredeemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x03R\x05point\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonB,Z*reward-service/internal/pb/redeem;redeempbb\x06proto3"

var (
	file_proto_reward_redeem_proto_rawDescOnce sync.Once
	file_proto_reward_redeem_proto_rawDescData []byte
)

func file_proto_reward_redeem_proto_rawDescGZIP() []byte {
	file_proto_reward_redeem_proto_rawDescOnce.Do(func() {
		file_proto_reward_redeem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reward_redeem_proto_rawDesc), len(file_proto_reward_redeem_proto_rawDesc)))
	})
	return file_proto_reward_redeem_proto_rawDescData
}

var file_proto_reward_redeem_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_reward_redeem_proto_goTypes = []any{
	(*RedeemRequest)(nil), // 0: reward.redeem.RedeemRequest
	(*RedeemResult)(nil),  // 1: reward.redeem.RedeemResult
}
var file_proto_reward_redeem_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reward_redeem_proto_init() }
func file_proto_reward_redeem_proto_init() {
	if File_proto_reward_redeem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reward_redeem_proto_rawDesc), len(file_proto_reward_redeem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reward_redeem_proto_goTypes,
		DependencyIndexes: file_proto_reward_redeem_proto_depIdxs,
		MessageInfos:      file_proto_reward_redeem_proto_msgTypes,
	}.Build()
	File_proto_reward_redeem_proto = out.File
	file_proto_reward_redeem_proto_goTypes = nil
	file_proto_reward_redeem_proto_depIdxs = nil
}
