// proto/reward_coupon.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/reward_coupon.proto

package reward

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =========================
// Inbound Event
// =========================
type RewardCouponRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardCouponRequested) Reset() {
	*x = RewardCouponRequested{}
	mi := &file_proto_reward_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardCouponRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardCouponRequested) ProtoMessage() {}

func (x *RewardCouponRequested) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reward_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardCouponRequested.ProtoReflect.Descriptor instead.
func (*RewardCouponRequested) Descriptor() ([]byte, []int) {
	return file_proto_reward_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *RewardCouponRequested) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RewardCouponRequested) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RewardCouponRequested) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

// =========================
// Outbound Event
// =========================
type UserCouponCreated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId   string                 `protobuf:"bytes,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode     string                 `protobuf:"bytes,3,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	MinPrice       int64                  `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxDiscount    int64                  `protobuf:"varint,6,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	ExpiredAt      int64                  `protobuf:"varint,7,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // unix timestamp
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp
	PolicyVersion  string                 `protobuf:"bytes,9,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserCouponCreated) Reset() {
	*x = UserCouponCreated{}
	mi := &file_proto_reward_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponCreated) ProtoMessage() {}

func (x *UserCouponCreated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reward_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponCreated.ProtoReflect.Descriptor instead.
func (*UserCouponCreated) Descriptor() ([]byte, []int) {
	return file_proto_reward_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *UserCouponCreated) GetUserCouponId() string {
	if x != nil {
		return x.UserCouponId
	}
	return ""
}

func (x *UserCouponCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCouponCreated) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *UserCouponCreated) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *UserCouponCreated) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *UserCouponCreated) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *UserCouponCreated) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *UserCouponCreated) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserCouponCreated) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

var File_proto_reward_coupon_proto protoreflect.FileDescriptor

const file_proto_reward_coupon_proto_rawDesc = "" +
	"\n" +
	"\x19proto/reward_coupon.proto\x12\x06reward\"e\n" +
	"\x15RewardCouponRequested\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x03R\x05point\"\xc1\x02\n" +
	"\x11UserCouponCreated\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\tR\fuserCouponId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x03 \x01(\tR\n" +
	"couponCode\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x03R\x0ediscountAmount\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x03R\bminPrice\x12!\n" +
	"\fmax_discount\x18\x06 \x01(\x03R\vmaxDiscount\x12\x1d\n" +
	"\n" +
	"expired_at\x18\a \x01(\x03R\texpiredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12%\n" +
	"\x0epolicy_version\x18\t \x01(\tR\rpolicyVersionB Z\x1ecoupon-service/proto/pb/rewardb\x06proto3"

var (
	file_proto_reward_coupon_proto_rawDescOnce sync.Once
	file_proto_reward_coupon_proto_rawDescData []byte
)

func file_proto_reward_coupon_proto_rawDescGZIP() []byte {
	file_proto_reward_coupon_proto_rawDescOnce.Do(func() {
		file_proto_reward_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reward_coupon_proto_rawDesc), len(file_proto_reward_coupon_proto_rawDesc)))
	})
	return file_proto_reward_coupon_proto_rawDescData
}

var file_proto_reward_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_reward_coupon_proto_goTypes = []any{
	(*RewardCouponRequested)(nil), // 0: reward.RewardCouponRequested
	(*UserCouponCreated)(nil),     // 1: reward.UserCouponCreated
}
var file_proto_reward_coupon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reward_coupon_proto_init() }
func file_proto_reward_coupon_proto_init() {
	if File_proto_reward_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reward_coupon_proto_rawDesc), len(file_proto_reward_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_reward_coupon_proto_goTypes,
		DependencyIndexes: file_proto_reward_coupon_proto_depIdxs,
		MessageInfos:      file_proto_reward_coupon_proto_msgTypes,
	}.Build()
	File_proto_reward_coupon_proto = out.File
	file_proto_reward_coupon_proto_goTypes = nil
	file_proto_reward_coupon_proto_depIdxs = nil
}
