// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/order_service.proto

package coupon_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	OrderTotal    float64                `protobuf:"fixed64,3,opt,name=order_total,json=orderTotal,proto3" json:"order_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCouponRequest) Reset() {
	*x = ApplyCouponRequest{}
	mi := &file_proto_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCouponRequest) ProtoMessage() {}

func (x *ApplyCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCouponRequest.ProtoReflect.Descriptor instead.
func (*ApplyCouponRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApplyCouponRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *ApplyCouponRequest) GetOrderTotal() float64 {
	if x != nil {
		return x.OrderTotal
	}
	return 0
}

type ApplyCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalTotal    float64                `protobuf:"fixed64,1,opt,name=final_total,json=finalTotal,proto3" json:"final_total,omitempty"`
	Discount      float64                `protobuf:"fixed64,2,opt,name=discount,proto3" json:"discount,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCouponResponse) Reset() {
	*x = ApplyCouponResponse{}
	mi := &file_proto_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCouponResponse) ProtoMessage() {}

func (x *ApplyCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCouponResponse.ProtoReflect.Descriptor instead.
func (*ApplyCouponResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyCouponResponse) GetFinalTotal() float64 {
	if x != nil {
		return x.FinalTotal
	}
	return 0
}

func (x *ApplyCouponResponse) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *ApplyCouponResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ApplyCouponResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_order_service_proto protoreflect.FileDescriptor

const file_proto_order_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/order_service.proto\x12\x0ecoupon_service\"o\n" +
	"\x12ApplyCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x02 \x01(\tR\n" +
	"couponCode\x12\x1f\n" +
	"\vorder_total\x18\x03 \x01(\x01R\n" +
	"orderTotal\"\x82\x01\n" +
	"\x13ApplyCouponResponse\x12\x1f\n" +
	"\vfinal_total\x18\x01 \x01(\x01R\n" +
	"finalTotal\x12\x1a\n" +
	"\bdiscount\x18\x02 \x01(\x01R\bdiscount\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2g\n" +
	"\rCouponService\x12V\n" +
	"\vApplyCoupon\x12\".coupon_service.ApplyCouponRequest\x1a#.coupon_service.ApplyCouponResponseB(Z&coupon-service/proto/pb/coupon_serviceb\x06proto3"

var (
	file_proto_order_service_proto_rawDescOnce sync.Once
	file_proto_order_service_proto_rawDescData []byte
)

func file_proto_order_service_proto_rawDescGZIP() []byte {
	file_proto_order_service_proto_rawDescOnce.Do(func() {
		file_proto_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_service_proto_rawDesc), len(file_proto_order_service_proto_rawDesc)))
	})
	return file_proto_order_service_proto_rawDescData
}

var file_proto_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_order_service_proto_goTypes = []any{
	(*ApplyCouponRequest)(nil),  // 0: coupon_service.ApplyCouponRequest
	(*ApplyCouponResponse)(nil), // 1: coupon_service.ApplyCouponResponse
}
var file_proto_order_service_proto_depIdxs = []int32{
	0, // 0: coupon_service.CouponService.ApplyCoupon:input_type -> coupon_service.ApplyCouponRequest
	1, // 1: coupon_service.CouponService.ApplyCoupon:output_type -> coupon_service.ApplyCouponResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_service_proto_init() }
func file_proto_order_service_proto_init() {
	if File_proto_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_service_proto_rawDesc), len(file_proto_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_service_proto_goTypes,
		DependencyIndexes: file_proto_order_service_proto_depIdxs,
		MessageInfos:      file_proto_order_service_proto_msgTypes,
	}.Build()
	File_proto_order_service_proto = out.File
	file_proto_order_service_proto_goTypes = nil
	file_proto_order_service_proto_depIdxs = nil
}
