// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/trip_event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event เมื่อ trip จบแล้ว
type TripEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"` // ใช้เป็น RefID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripEvent) Reset() {
	*x = TripEvent{}
	mi := &file_proto_trip_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripEvent) ProtoMessage() {}

func (x *TripEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripEvent.ProtoReflect.Descriptor instead.
func (*TripEvent) Descriptor() ([]byte, []int) {
	return file_proto_trip_event_proto_rawDescGZIP(), []int{0}
}

func (x *TripEvent) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TripEvent) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

var File_proto_trip_event_proto protoreflect.FileDescriptor

const file_proto_trip_event_proto_rawDesc = "" +
	"\n" +
	"\x16proto/trip_event.proto\x12\freward.event\"S\n" +
	"\tTripEvent\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x03R\x05pointB*Z(reward-service/internal/pb/event;eventpbb\x06proto3"

var (
	file_proto_trip_event_proto_rawDescOnce sync.Once
	file_proto_trip_event_proto_rawDescData []byte
)

func file_proto_trip_event_proto_rawDescGZIP() []byte {
	file_proto_trip_event_proto_rawDescOnce.Do(func() {
		file_proto_trip_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_event_proto_rawDesc), len(file_proto_trip_event_proto_rawDesc)))
	})
	return file_proto_trip_event_proto_rawDescData
}

var file_proto_trip_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_trip_event_proto_goTypes = []any{
	(*TripEvent)(nil), // 0: reward.event.TripEvent
}
var file_proto_trip_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trip_event_proto_init() }
func file_proto_trip_event_proto_init() {
	if File_proto_trip_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_event_proto_rawDesc), len(file_proto_trip_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trip_event_proto_goTypes,
		DependencyIndexes: file_proto_trip_event_proto_depIdxs,
		MessageInfos:      file_proto_trip_event_proto_msgTypes,
	}.Build()
	File_proto_trip_event_proto = out.File
	file_proto_trip_event_proto_goTypes = nil
	file_proto_trip_event_proto_depIdxs = nil
}
