// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/coupon_event.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponEventType int32

const (
	CouponEventType_CREATED     CouponEventType = 0
	CouponEventType_UPDATED     CouponEventType = 1
	CouponEventType_DEACTIVATED CouponEventType = 2
)

// Enum value maps for CouponEventType.
var (
	CouponEventType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DEACTIVATED",
	}
	CouponEventType_value = map[string]int32{
		"CREATED":     0,
		"UPDATED":     1,
		"DEACTIVATED": 2,
	}
)

func (x CouponEventType) Enum() *CouponEventType {
	p := new(CouponEventType)
	*p = x
	return p
}

func (x CouponEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coupon_event_proto_enumTypes[0].Descriptor()
}

func (CouponEventType) Type() protoreflect.EnumType {
	return &file_proto_coupon_event_proto_enumTypes[0]
}

func (x CouponEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponEventType.Descriptor instead.
func (CouponEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_coupon_event_proto_rawDescGZIP(), []int{0}
}

type CouponEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CouponEventType        `protobuf:"varint,1,opt,name=type,proto3,enum=coupon.CouponEventType" json:"type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,3,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	DiscountType  string                 `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue float64                `protobuf:"fixed64,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	MinOrder      float64                `protobuf:"fixed64,6,opt,name=min_order,json=minOrder,proto3" json:"min_order,omitempty"`
	MaxDiscount   float64                `protobuf:"fixed64,7,opt,name=max_discount,json=maxDiscount,proto3" json:"max_discount,omitempty"`
	MaxUsage      int32                  `protobuf:"varint,8,opt,name=max_usage,json=maxUsage,proto3" json:"max_usage,omitempty"`
	ValidFrom     string                 `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       string                 `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponEvent) Reset() {
	*x = CouponEvent{}
	mi := &file_proto_coupon_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponEvent) ProtoMessage() {}

func (x *CouponEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coupon_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponEvent.ProtoReflect.Descriptor instead.
func (*CouponEvent) Descriptor() ([]byte, []int) {
	return file_proto_coupon_event_proto_rawDescGZIP(), []int{0}
}

func (x *CouponEvent) GetType() CouponEventType {
	if x != nil {
		return x.Type
	}
	return CouponEventType_CREATED
}

func (x *CouponEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CouponEvent) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *CouponEvent) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *CouponEvent) GetDiscountValue() float64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CouponEvent) GetMinOrder() float64 {
	if x != nil {
		return x.MinOrder
	}
	return 0
}

func (x *CouponEvent) GetMaxDiscount() float64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CouponEvent) GetMaxUsage() int32 {
	if x != nil {
		return x.MaxUsage
	}
	return 0
}

func (x *CouponEvent) GetValidFrom() string {
	if x != nil {
		return x.ValidFrom
	}
	return ""
}

func (x *CouponEvent) GetValidTo() string {
	if x != nil {
		return x.ValidTo
	}
	return ""
}

var File_proto_coupon_event_proto protoreflect.FileDescriptor

const file_proto_coupon_event_proto_rawDesc = "" +
	"\n" +
	"\x18proto/coupon_event.proto\x12\x06coupon\"\xd7\x02\n" +
	"\vCouponEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.coupon.CouponEventTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcoupon_code\x18\x03 \x01(\tR\n" +
	"couponCode\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\x01R\rdiscountValue\x12\x1b\n" +
	"\tmin_order\x18\x06 \x01(\x01R\bminOrder\x12!\n" +
	"\fmax_discount\x18\a \x01(\x01R\vmaxDiscount\x12\x1b\n" +
	"\tmax_usage\x18\b \x01(\x05R\bmaxUsage\x12\x1d\n" +
	"\n" +
	"valid_from\x18\t \x01(\tR\tvalidFrom\x12\x19\n" +
	"\bvalid_to\x18\n" +
	" \x01(\tR\avalidTo*<\n" +
	"\x0fCouponEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\x0f\n" +
	"\vDEACTIVATED\x10\x02B Z\x1ecoupon-service/proto/pb/couponb\x06proto3"

var (
	file_proto_coupon_event_proto_rawDescOnce sync.Once
	file_proto_coupon_event_proto_rawDescData []byte
)

func file_proto_coupon_event_proto_rawDescGZIP() []byte {
	file_proto_coupon_event_proto_rawDescOnce.Do(func() {
		file_proto_coupon_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coupon_event_proto_rawDesc), len(file_proto_coupon_event_proto_rawDesc)))
	})
	return file_proto_coupon_event_proto_rawDescData
}

var file_proto_coupon_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_coupon_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_coupon_event_proto_goTypes = []any{
	(CouponEventType)(0), // 0: coupon.CouponEventType
	(*CouponEvent)(nil),  // 1: coupon.CouponEvent
}
var file_proto_coupon_event_proto_depIdxs = []int32{
	0, // 0: coupon.CouponEvent.type:type_name -> coupon.CouponEventType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_coupon_event_proto_init() }
func file_proto_coupon_event_proto_init() {
	if File_proto_coupon_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coupon_event_proto_rawDesc), len(file_proto_coupon_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_coupon_event_proto_goTypes,
		DependencyIndexes: file_proto_coupon_event_proto_depIdxs,
		EnumInfos:         file_proto_coupon_event_proto_enumTypes,
		MessageInfos:      file_proto_coupon_event_proto_msgTypes,
	}.Build()
	File_proto_coupon_event_proto = out.File
	file_proto_coupon_event_proto_goTypes = nil
	file_proto_coupon_event_proto_depIdxs = nil
}
